### ISSUE TITLE
# 4-2. ワード編集画面

### ISSUE THREAD

**Issue by Hiruyan-J** [RUNTEQ-62-GROUP-DEVELOPMENT/Group1#18]
# 概要
ワード編集画面の実装
機能内容は、[# 04_ワード登録 / 詳細画面の作成](https://github.com/RUNTEQ-62-GROUP-DEVELOPMENT/Group1/issues/8#issue-2812826812)を参照
  
![Image](https://github.com/user-attachments/assets/dbc71545-8884-4ac0-ad3e-6ff16b19fcbb)
  
## 実装概要
- ワード編集機能
  - [x] ルーティングの設定(resources :posts)
    - edit
    - update
  - [x] コントローラにアクションの作成
    - [x] edit
    - [x] update
  - [x] ビューの作成
    - [x] edit
      - _formを呼び出し
- フラッシュメッセージ
  - [x] 編集成功時：ワード詳細画面で「ワードを更新しました」
    - [x] posts#updateに記載
  - [x] 編集失敗時：ワード編集画面で「ワードを更新できませんでした」
    - [x] posts#updateに記載
- ~~[フォーム入力時エラー情報表示](https://school.runteq.jp/v3/curriculums/rails_basic/chapters/9)の確認~~
  - [# 4-4-1. 共通機能：フォーム入力時エラー情報パーシャル](https://github.com/RUNTEQ-62-GROUP-DEVELOPMENT/Group1/issues/26)で実施予定
- ログインユーザーのみのアクセス制限がかかっていることの確認
  - [x] 未ログインユーザーがアクセス→ログイン画面へ遷移・flash「ログインしてください」
- [x] ワード投稿主のみアクセス可能なことの確認
- i18n対応
  - [x] config/locales/views/ja.ymlを編集
    ```
    ja:
      helpers:
        submit:
          update: 更新
    ```
    ```
      defaults:
        flash_message:
          updated: "%{item}を更新しました"
          not_updated: "%{item}を更新出来ませんでした"
    ```
    ```
      posts:
        edit:
          title: ワード編集
    ```

## 参考カリキュラム
- [Rails基礎13](https://school.runteq.jp/v3/curriculums/rails_basic/chapters/13)
- フラッシュメッセージ：[Rails基礎5](https://school.runteq.jp/v3/curriculums/rails_basic/chapters/5)
- フォーム入力時エラー情報表示：[Rails基礎9](https://school.runteq.jp/v3/curriculums/rails_basic/chapters/9)
